services:

  mysql:
    image: mysql:8.0
    container_name: inventory-mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: inventory_dashboard

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:

    build:
      context: ./backend

    container_name: inventory-backend

    depends_on:
      - mysql

    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root123
      DB_NAME: inventory_dashboard

    ports:
      - "3000:3000"

  frontend:

    build:
      context: ./frontend

    container_name: inventory-frontend

    depends_on:
      - backend

    ports:
      - "5173:80"

volumes:

  mysql-data: