apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-backend
  namespace: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-backend
  template:
    metadata:
      labels:
        app: inventory-backend
    spec:
      containers:
        - name: inventory-backend
          image: 176728675662.dkr.ecr.us-east-1.amazonaws.com/inventory-backend:v1
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: inventory-db
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
