apiVersion: v1
kind: Service
metadata:
  name: inventory-backend
  namespace: inventory
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  selector:
    app: inventory-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
